### ISSUE TITLE
Dependency of "footprint" module not present on package.json

### ISSUE THREAD

**Issue by tombatossals** [danielzzz/node-ping#11]
Hi, I'm trying to use "node-ping" on my project but there seems to be a dependency with a "footprint" module:

```
Error: Cannot find module 'footprint'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/dave/gps/node_modules/node-ping/context.js:3:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Can you include this module in the dependencies section of package.json?

**Comment by mattce** [comment]
As probably someone else might stumble upon the same issue:
Although this repository is named `node-ping` the package on the npm registry is just called  `ping`.
Installing `node-ping` resolves into the before mentioned error. If you have a closer look at the logged output you can see that he tries executes something inside `context.js` which itself is inside the `node-ping` package which itself is not part of this very rpackage.

**Comment by shennan** [comment]
> As probably someone else might stumble upon the same issue: Although this repository is named `node-ping` the package on the npm registry is just called `ping`. Installing `node-ping` resolves into the before mentioned error. If you have a closer look at the logged output you can see that he tries executes something inside `context.js` which itself is inside the `node-ping` package which itself is not part of this very package.

This was the issue. Thanks.
