### ISSUE TITLE
Not working on W10 with 'localhost' or '127.0.0.1'

### ISSUE THREAD

**Issue by jpablogn** [danielzzz/node-ping#113]
Hello,
It works fine with othe IPs, but not with 'localhost' o '127.0.0.1', ¿why?.
I use it like that for tests.
Thank you.
J. Pablo.

**Comment by mondwan** [comment]
Did u try to ping these 2 ip address on your local terminal with system
ping?

在 2020年3月12日週四 05:02，Juan Pablo García Nieto <notifications@github.com> 寫道：

**Comment by jpablogn** [comment]
Hello.
Both works fine from windows command console and they also work with "tcp-ping" node package, but they are not working 'ping' package.
Thank you.

**Comment by mondwan** [comment]
May be, you can capture the error from the promise form, and paste here.

Also, please paste the output from your window console here

在 2020年3月13日週五 03:04，Juan Pablo García Nieto <notifications@github.com> 寫道：

**Comment by jpablogn** [comment]
Two cases:
- First (ping to google): OK
- Second (ping to 127.0.0.1): Error

C:\temporal\_TrenDigital\scripts\0010_tests\tests>**node ping**
host www.google.com is alive

C:\temporal\_TrenDigital\scripts\0010_tests\tests>**node ping**
C:\temporal\_TrenDigital\scripts\0010_tests\tests\node_modules\ping\lib\parser\win.js:56
        this._times.push(parseFloat(match[1], 10));
                                         ^

TypeError: Cannot read property '1' of null
    at WinParser._processBody (C:\temporal\_TrenDigital\scripts\0010_tests\tests\node_modules\ping\lib\parser\win.js:56:42)
    at WinParser.parser.eat (C:\temporal\_TrenDigital\scripts\0010_tests\tests\node_modules\ping\lib\parser\base.js:125:14)
    at C:\temporal\_TrenDigital\scripts\0010_tests\tests\node_modules\underscore\underscore.js:76:21
    at Function._.each._.forEach (C:\temporal\_TrenDigital\scripts\0010_tests\tests\node_modules\underscore\underscore.js:186:9)
    at ChildProcess.<anonymous> (C:\temporal\_TrenDigital\scripts\0010_tests\tests\node_modules\ping\lib\ping-promise.js:76:12)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

**Comment by stark-ace-1891** [comment]
Modify the win.js file
The error is due to the fact that in the code it looks for the text 'ms' and when it does not get results it gets an undefined in the variable' timeKVP ', sometimes when the answer is very fast the text does not contain this text but if the' m ', for this reason we modify line 55 as follows:
![stake](https://user-images.githubusercontent.com/62627965/77488037-11739980-6e02-11ea-87df-746138f822a4.JPG)

**Comment by jpablogn** [comment]
Right!!, that solves the problem!.
Thank you.

**Comment by mondwan** [comment]
Sort of related to #110. Close and refer to discussions there
